### ISSUE TITLE
country

### ISSUE THREAD

**Issue by boussarilatif** [beyondplus/flags-dropdown-vue#2]
how to select europe or africa country only

**Comment by sanpwintthu** [comment]
Sorry , We didn't found europe or africa  flag image in our database. We only found  South Africa . 
"iso": "za",
"nicename": "South Africa",
https://countrycode.org/southafrica

if you needed , pls provide  iso and flag images.  Thank

**Comment by boussarilatif** [comment]
in fact you didn't understand me.
I just want to take back five countries from Europe and delete all the others.
I have every country in the world with flags-dropdown-view

**Comment by boussarilatif** [comment]
thank you I managed to fix this by deleting some countries in the flagdropdown.vue file
